# Site settings
name: 想先生
location: 北京
#company: IBM
position: Java开发工程师
github: https://gitee.com/Array_Xiang
facebook: https://www.facebook.com/profile.php?id=100090009371849
phone: 15279151605
email: arrayxiangxiang@gmail.com

baseurl: "/resume.io"

permalink: /:year/:month/:day/:title/

exclude: ['README.md']

# Build settings
markdown: kramdown

